apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-machine-set-operator
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-machine-set-operator
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
  - apiGroups:
      - machine.openshift.io
    resources:
      - machines
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - machine.openshift.io
    resources:
      - controlplanemachinesets/status
      - controlplanemachinesets/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups:
      - machine.openshift.io
    resources:
      - controlplanemachinesets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete

  - apiGroups:
      - machine.openshift.io
    resources:
      - machinesets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-plane-machine-set-operator
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusteroperators/status
    verbs:
      - create
      - get
      - update
      - list
      - watch

  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - list
      - patch

  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: control-plane-machine-set-operator
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: control-plane-machine-set-operator
subjects:
  - kind: ServiceAccount
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane-machine-set-operator
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: MachineAPI
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-plane-machine-set-operator
subjects:
  - kind: ServiceAccount
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
