apiVersion: v1
kind: Service
metadata:
  name: control-plane-machine-set-operator
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: MachineAPI
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: control-plane-machine-set-operator-tls
  labels:
    k8s-app: control-plane-machine-set-operator
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 9443
    targetPort: https
  selector:
    k8s-app: control-plane-machine-set-operator
  sessionAffinity: None
