apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: control-plane-machine-set
  annotations:
    capability.openshift.io/name: MachineAPI
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
  - group: ""
    name: openshift-machine-api
    resource: namespaces
  - group: machine.openshift.io
    name: ""
    resource: controlplanemachinesets
  - group: machine.openshift.io
    name: ""
    resource: machines
  - group: ""
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
    resource: serviceaccounts
  - group: ""
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
    resource: services
  - group: apps
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
    resource: deployments
  - group: rbac.authorization.k8s.io
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
    resource: roles
  - group: rbac.authorization.k8s.io
    name: control-plane-machine-set-operator
    namespace: openshift-machine-api
    resource: rolebindings
  - group: rbac.authorization.k8s.io
    name: control-plane-machine-set-operator
    resource: clusterroles
  - group: rbac.authorization.k8s.io
    name: control-plane-machine-set-operator
    resource: clusterrolebindings
  - group: admissionregistration.k8s.io
    name: controlplanemachineset.machine.openshift.io
    resource: validatingwebhookconfigurations
