//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSFailureDomain) DeepCopyInto(out *AWSFailureDomain) {
	*out = *in
	in.Subnet.DeepCopyInto(&out.Subnet)
	out.Placement = in.Placement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSFailureDomain.
func (in *AWSFailureDomain) DeepCopy() *AWSFailureDomain {
	if in == nil {
		return nil
	}
	out := new(AWSFailureDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSFailureDomainPlacement) DeepCopyInto(out *AWSFailureDomainPlacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSFailureDomainPlacement.
func (in *AWSFailureDomainPlacement) DeepCopy() *AWSFailureDomainPlacement {
	if in == nil {
		return nil
	}
	out := new(AWSFailureDomainPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFailureDomain) DeepCopyInto(out *AzureFailureDomain) {
	*out = *in
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFailureDomain.
func (in *AzureFailureDomain) DeepCopy() *AzureFailureDomain {
	if in == nil {
		return nil
	}
	out := new(AzureFailureDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSet) DeepCopyInto(out *ControlPlaneMachineSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSet.
func (in *ControlPlaneMachineSet) DeepCopy() *ControlPlaneMachineSet {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneMachineSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSetList) DeepCopyInto(out *ControlPlaneMachineSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneMachineSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSetList.
func (in *ControlPlaneMachineSetList) DeepCopy() *ControlPlaneMachineSetList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneMachineSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSetSpec) DeepCopyInto(out *ControlPlaneMachineSetSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Strategy = in.Strategy
	in.FailureDomains.DeepCopyInto(&out.FailureDomains)
	in.Selector.DeepCopyInto(&out.Selector)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSetSpec.
func (in *ControlPlaneMachineSetSpec) DeepCopy() *ControlPlaneMachineSetSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSetStatus) DeepCopyInto(out *ControlPlaneMachineSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSetStatus.
func (in *ControlPlaneMachineSetStatus) DeepCopy() *ControlPlaneMachineSetStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSetStrategy) DeepCopyInto(out *ControlPlaneMachineSetStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSetStrategy.
func (in *ControlPlaneMachineSetStrategy) DeepCopy() *ControlPlaneMachineSetStrategy {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSetStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMachineSetTemplate) DeepCopyInto(out *ControlPlaneMachineSetTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMachineSetTemplate.
func (in *ControlPlaneMachineSetTemplate) DeepCopy() *ControlPlaneMachineSetTemplate {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMachineSetTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureDomains) DeepCopyInto(out *FailureDomains) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new([]AWSFailureDomain)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AWSFailureDomain, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new([]AzureFailureDomain)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AzureFailureDomain, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new([]GCPFailureDomain)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GCPFailureDomain, len(*in))
			copy(*out, *in)
		}
	}
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = new([]OpenStackFailureDomain)
		if **in != nil {
			in, out := *in, *out
			*out = make([]OpenStackFailureDomain, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureDomains.
func (in *FailureDomains) DeepCopy() *FailureDomains {
	if in == nil {
		return nil
	}
	out := new(FailureDomains)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPFailureDomain) DeepCopyInto(out *GCPFailureDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPFailureDomain.
func (in *GCPFailureDomain) DeepCopy() *GCPFailureDomain {
	if in == nil {
		return nil
	}
	out := new(GCPFailureDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackFailureDomain) DeepCopyInto(out *OpenStackFailureDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackFailureDomain.
func (in *OpenStackFailureDomain) DeepCopy() *OpenStackFailureDomain {
	if in == nil {
		return nil
	}
	out := new(OpenStackFailureDomain)
	in.DeepCopyInto(out)
	return out
}
